services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: whiplash-backend:local
    environment:
      - PORT=${PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3001:${PORT}"

  redis:
    image: redis:8.2.1-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    